### ISSUE TITLE
The library fails under the Windows Server

### ISSUE THREAD

**Issue by poipoiPIO** [Kalmat/PyMonCtl#4]
#### Description
It looks like the library actively uses `GetAwarenessFromDpiAwarenessContext` function of winapi, which is [unavailable](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getawarenessfromdpiawarenesscontext) on any version of windows server. And when it comes to [this line](https://github.com/Kalmat/PyMonCtl/blob/acf1dd188768b7ccc41ece8504201ddeeba89fb6/src/pymonctl/_pymonctl_win.py#L28), execution is failing with `AttributeError: function 'GetAwarenessFromDpiAwarenessContext' not found` exception.

#### Possible Solution
Wrap  the `GetAwarenessFromDpiAwarenessContext` call into the try-except clause on attribute error and assign zero to `dpiAware` variable [here](https://github.com/Kalmat/PyMonCtl/blob/acf1dd188768b7ccc41ece8504201ddeeba89fb6/src/pymonctl/_pymonctl_win.py#L28):

```python
try:
    dpiAware = ctypes.windll.user32.GetAwarenessFromDpiAwarenessContext(ctypes.windll.user32.GetThreadDpiAwarenessContext())
except AttributeError:
    dpiAware = 0
```

#### Also:
Looks like [here](https://github.com/Kalmat/PyWinBox/blob/8029098f57ce99fb08aefffbb3ec9dafb2caaf61/src/pywinbox/_pywinbox_win.py#L17) is also this issue with PyWinBox library

If the try-catch workaround is okay, I could suggest a pull request with changes 
Best regards, Lappely <3

**Comment by Kalmat** [comment]
Hi! Thank you SO MUCH for your feedback and help! I didn't test this in Windows Server, sorry, so thank you for finding and pointing out this issue! I fully agree with your proposed solution in both, PyMonCtl and PyWinBox.

There is something I would like to know/test in addition: after getting current DpiAwareness value and, in case it is 0, the module tries to set it to 2, using `ctypes.windll.shcore.SetProcessDpiAwareness(2)`... Will this sentence work in Windows Server, or should it be moved inside the try-except block as well?

Thank you again!
